[Eth]
NetworkId = 1682
NoPruning = false
NoPrefetch = false
TrieTimeout = 2000000000000
EnablePreimageRecording = false

[Eth.Miner]
GasFloor = 30000000
GasCeil = 40000000
GasPrice = 1000000000
Recommit = 10000000000

[Eth.TxPool]
Locals = []
NoLocals = true
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 1000000000
PriceBump = 10
AccountSlots = 512
GlobalSlots = 10000
AccountQueue = 256
GlobalQueue = 5000
Lifetime = 10800000000000

[Eth.GPO]
Blocks = 20
Percentile = 60
OracleThreshold = 20

[Node]
IPCPath = "geth.ipc"
HTTPHost = "0.0.0.0"
InsecureUnlockAllowed = false
HTTPPort = 8545
HTTPCors = ["*"]
HTTPVirtualHosts = ["*"]
HTTPModules = ["eth", "net", "web3", "txpool", "debug"]
WSHost = "0.0.0.0"
WSPort = 8546
WSOrigins = ["*"]
WSModules = ["eth", "net", "web3", "txpool", "debug"]

[Node.P2P]
MaxPeers = 30
NoDiscovery = false
StaticNodes = []
TrustedNodes = []
ListenAddr = ":30311"
EnableMsgEvents = false

[Node.HTTPTimeouts]
ReadTimeout = 30000000000
WriteTimeout = 30000000000
IdleTimeout = 120000000000

[Node.LogConfig]
FilePath = "bsc.log"
TimeFormat = "01-02|15:04:05.000"
MaxBackups = 24
MaxBytesSize = 10485760
Level = "info"
FileRoot = ""

[Metrics]
Enabled = true
EnabledExpensive = true
HTTP = "0.0.0.0"
Port = 6060